### ISSUE TITLE
Windows has issues with initial thickness value being not set

### ISSUE THREAD

**Issue by Cjreynol** [Cjreynol/pypaint#4]
Exception in Tkinter callback
Traceback (most recent call last):
  File "\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "\pypaint\paint_controller.py", line 140, in handle_event
    self._is_draggable(self.current_mode))
  File "\pypaint\paint_controller.py", line 159, in _handle_drawing
    self._handle_button_release_event(event, drawing_type, drag_drawing)
  File "\pypaint\paint_controller.py", line 187, in _handle_button_release_event
    drawing = Drawing(drawing_type, self.thickness_value,
AttributeError: 'PaintController' object has no attribute 'thickness_value'

**Comment by Cjreynol** [comment]
Should be fixed now in e9e089071bdbebab64cf82c613dac1ca752ccdc7
